{
 "title": "CyberSecurity Challenge Belgium 2024",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"height:100%\">\n  <img style=\"height:100%\" src=\"https://i.imgur.com/64oKLen.png\">\n</div>"
   },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "🕒 Remaining Time",
   "type": "grafana-clock-panel",
   "description": "Online Qualifiers ➞ 08 March (10:00) - 09 March (18:00)\n\nFinals Brussels ➞ 22 - 23 March",
   "gridPos": { "h": 2, "w": 8, "x": 5, "y": 0 }
  },
  {
   "title": "👤 Participants",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(timestamp) as time, 'Total Students' as metric, COUNT(*) AS value\nFROM (\n    SELECT timestamp, UNNEST(string_to_array(institutions, ',')) AS institution\n    FROM scoreboard\n    WHERE timestamp = (SELECT MAX(timestamp) FROM scoreboard)\n) AS institutions_table;"
    }
   ]
  },
  {
   "title": "👥 Teams",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(team_id)\nFROM scoreboard\nWHERE timestamp = (SELECT MAX(timestamp) FROM scoreboard)"
    }
   ]
  },
  {
   "title": "📊 Average Score",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(score)\nFROM scoreboard\nWHERE timestamp = (SELECT MAX(timestamp) FROM scoreboard)"
    }
   ]
  },
  {
   "title": "🖥 GitHub",
   "type": "text",
   "description": "💙 Made with Love",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 0 },
   "options": {
    "content": "<a href=\"https://www.youtube.com/watch?v=WtO3AHMBePY\" target=\"_blank\" style=\"color:#00e1ff; font-weight: bold;\">➞ Source Code</a>"
   },
   "targets": [
    {
     "rawSql": "SELECT MAX(timestamp) as time, 'Total Students' as metric, COUNT(*) AS value\nFROM (\n    SELECT timestamp, UNNEST(string_to_array(institutions, ',')) AS institution\n    FROM scoreboard\n    WHERE timestamp = (SELECT MAX(timestamp) FROM scoreboard)\n) AS institutions_table;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "options": {
    "content": "<div style=\"height:100%; display:flex; justify-content: right;\">\n  <img style=\"height:100%\" src=\"https://i.imgur.com/pHLhMap.png\">\n</div>"
   },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "📈 Scoreboard",
   "type": "timeseries",
   "description": "The scoreboard is updated every minute !",
   "gridPos": { "h": 16, "w": 19, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT \n  \"timestamp\" AS \"time\", \n  score AS \"value\", \n  CASE \n    WHEN length(team_name) <= 20 THEN team_name \n    ELSE LEFT(team_name, 20) || '...' \n  END AS \"metric\"\nFROM scoreboard \nWHERE \n  \"timestamp\" >= $__timeFrom() AND \"timestamp\" <= $__timeTo() \nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "🎯 Score to be qualified",
   "type": "stat",
   "description": "To be qualified, your team need to be in the 40 first !",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  score AS \"value\", \n  team_name as \"metric\" \nFROM scoreboard \nORDER BY score ASC\nLIMIT 40;"
    }
   ]
  },
  {
   "title": "🎓 Students per Institutions",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT MAX(timestamp) as time, institution as metric, COUNT(institution) AS value\nFROM (\n    SELECT timestamp, UNNEST(string_to_array(institutions, ',')) AS institution\n    FROM scoreboard\n    WHERE timestamp = (SELECT MAX(timestamp) FROM scoreboard)\n) AS institutions_table\nGROUP BY institution;"
    }
   ]
  },
  {
   "title": "🥇 Top 10",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  score AS \"Score\", \n  team_name as \"metric\" \nFROM scoreboard \nORDER BY score DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "🪙 Top 40",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 14, "x": 10, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  score AS \"Score\", \n  CASE \n    WHEN length(team_name) <= 15 THEN team_name \n    ELSE LEFT(team_name, 15) || '...' \n  END as \"name\"\nFROM scoreboard \nORDER BY score DESC\nLIMIT 40;"
    }
   ]
  },
  {
   "title": "🏴 Last Challenge Solved",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE \n    WHEN length(team_name) <= 20 THEN team_name \n    ELSE LEFT(team_name, 20) || '...' \n  END AS \"Team\",\n  last_flag AS \"Challenge ID\"\nFROM scoreboard \nWHERE timestamp = (SELECT MAX(timestamp) from scoreboard)"
    }
   ]
  }
 ]
}